import { TextListView } from "../../components/list_view.slint";
import { ControlHint } from "../../components/control_hint.slint";

export component CoreList {
    in property <[string]> cores;

    callback on-cancel();
    callback on-core-selected(/* selected-item */ int);

    forward-focus: i-list;

    i-focus-scope := FocusScope {
        key-pressed(event) => {
            if (event.text == "b") {
                on-cancel();
                accept
            } else {
                reject
            }
        }

        VerticalLayout {
            spacing: 2px;

            init => {
                i-list.focus();
            }

            i-list := TextListView {
                model: root.cores;
                wrap: true;
                on-item-selected(i) => {
                    on-core-selected(i);
                }
            }

            HorizontalLayout {
                alignment: space-between;

                ControlHint {
                    label: "Back";
                    button: "b";
                }

                ControlHint {
                    label: "Select";
                    button: "a";
                }
            }
        }
    }
}
