import { ListViewBase } from "../../components/list_view.slint";
import { ControlHint } from "../../components/control_hint.slint";
import { CoreListInfo } from "types.slint";

component CoreListItem inherits HorizontalLayout {
    in property <CoreListInfo> core;
    padding: 2px;

    Text {
        text: core.core-name;
        horizontal-alignment: left;
        overflow: elide;
        min-width: 160px;
        horizontal-stretch: 2.0;
    }

    Text {
        text: core.core-author;
        horizontal-alignment: right;
        overflow: elide;
        color: #666;
        min-width: 80px;
        horizontal-stretch: 1.0;
    }
}


export component CoreList {
    in property <[CoreListInfo]> cores;

    callback on-cancel();
    callback on-core-selected(/* selected-item */ int);

    forward-focus: i-list;

    i-focus-scope := FocusScope {
        key-pressed(event) => {
            if (event.text == "b") {
                on-cancel();
                accept
            } else {
                reject
            }
        }

        VerticalLayout {
            spacing: 2px;

            i-list := ListViewBase {
                num-items: cores.length;
                wrap: true;

                for item[index] in cores: child-items := CoreListItem {
                    core: item;
                }

                on-item-selected(i) => {
                    on-core-selected(i);
                }
            }

            HorizontalLayout {
                alignment: space-between;

                ControlHint {
                    label: "Back";
                    button: "b";
                }

                ControlHint {
                    label: "Select";
                    button: "a";
                }
            }
        }
    }
}
