import { Global, ScreenId, Backend } from "../../common.slint";
import { ScreenBase } from "../../components/screen.slint";
import { TextListView } from "../../components/list_view.slint";
import { ControlHint } from "../../components/control_hint.slint";
import { CoreList } from "core_list.slint";
import { CoreDetails } from "core_detail.slint";
import { CoreListInfo } from "types.slint";

export component CoresScreen inherits ScreenBase {
    title: "Cores";

    // TODO dynamic
    in property <[CoreListInfo]> cores: [
        {
            core-name: "Game Boy / Game Boy Color",
            core-author: "Game Bub",
        },
        {
            core-name: "Game Boy Advance",
            core-author: "Game Bub",
        },
    ];
    private property <int> selected-core: -1;

    // Debug only
    // init => { selected-core = 0; }
    // width: 360px;
    // height: 240px;

    if selected-core == -1: CoreList {
        cores: cores;
        width: 100%;
        height: 100%;

        init => {
            self.focus();
        }

        on-cancel => {
            Global.set-screen(ScreenId.MainMenu);
        }
        on-core-selected(i) => {
            selected-core = i;
        }
    }

    if selected-core != -1: CoreDetails {
        width: 100%;
        height: 100%;

        init => {
            self.focus();
        }

        core-name: cores[selected-core].core-name;
        core-author: cores[selected-core].core-author;

        on-cancel => {
            selected-core = -1;
        }
    }
}
