import { Global, ScreenId, Backend } from "../../common.slint";
import { ScreenBase } from "../../components/screen.slint";
import { TextListView } from "../../components/list_view.slint";
import { ControlHint } from "../../components/control_hint.slint";
import { CoreList } from "core_list.slint";
import { CoreDetails } from "core_detail.slint";
import { CoreSubscreen, CoreListInfo } from "types.slint";
import { CoreFileSelect } from "core_file_select.slint";

export component CoresScreen inherits ScreenBase {
    title: "Cores";

    // TODO dynamic
    in property <[CoreListInfo]> cores: [
        {
            core-id: "Game-Bub.GB",
            core-name: "Game Boy / Game Boy Color",
            core-author: "Game Bub",
        },
        {
            core-id: "Game-Bub.GBA",
            core-name: "Game Boy Advance",
            core-author: "Game Bub",
        },
    ];
    private property <int> selected-core: -1;

    init => {
        Backend.core-subscreen = CoreSubscreen.List;
        selected-core = -1;
    }

    // Debug only
    // width: 360px;
    // height: 240px;

    if Backend.core-subscreen == CoreSubscreen.List: CoreList {
        cores: cores;
        width: 100%;
        height: 100%;

        init => {
            self.focus();
        }

        on-cancel => {
            Global.set-screen(ScreenId.MainMenu);
        }
        on-core-selected(i) => {
            selected-core = i;
            Backend.core-subscreen = CoreSubscreen.Detail;
        }
    }

    if Backend.core-subscreen == CoreSubscreen.Detail: CoreDetails {
        width: 100%;
        height: 100%;

        init => {
            // TODO: adjust screen title if coming back from File Select
            self.focus();
        }

        core-name: cores[selected-core].core-name;
        core-author: cores[selected-core].core-author;

        on-cancel => {
            Backend.core-subscreen = CoreSubscreen.List;
        }
        on-run => {
            Backend.core-run(cores[selected-core].core-id);
            // TODO: show loading screen?
        }
    }

    if Backend.core-subscreen == CoreSubscreen.FileSelect: CoreFileSelect {
        width: 100%;
        height: 100%;

        init => {
            self.focus();
        }
        on-cancel => {
            Backend.core-subscreen = CoreSubscreen.Detail;
            Backend.core-file-select-cancel();
        }
    }
}
