import { Global, ScreenId, Backend } from "../common.slint";
import { ScreenBase } from "../components/screen.slint";
import { Button } from "../components/button.slint";
import { ButtonList } from "../components/button_list.slint";

export component GameScreen inherits ScreenBase {
    private property <bool> paused: false;
    forward-focus: i-focus-scope;

    protected function set-paused(paused: bool) {
        Global.ui-status-bar = paused;
        Backend.game-set-paused(paused);
        self.paused = paused;
        if (paused) {
            i-list.focus();
        } else {
            i-focus-scope.focus();
        }
    }

    i-focus-scope := FocusScope {
        key-released(event) => {
            if (event.text == "Home" || event.text == "h") && !Global.home-consumed {
                set-paused(!root.paused);
            }
            if (event.text == "Power") {
                set-paused(true);
            }
            reject
        }

        menu := Rectangle {
            visible: paused;
            background: #FFF;
            border-color: black;
            border-width: 1px;
            width: i-list.min-width + 20px;
            height: i-list.min-height;

            i-list := ButtonList {
                items: ["Resume", "Reset", "Main Menu"];
                on-selected(item) => {
                    if (item == 0) {
                        root.set-paused(false);
                    } else if (item == 1) {
                        Backend.game-reset();
                        root.set-paused(false);
                    } else if (item == 2) {
                        Backend.game-exit();
                    }
                }
            }
        }

        if Backend.rom-select-is-loading:  Rectangle {
            background: #FFF;
            border-color: black;
            border-width: 1px;
            width: i-loading-layout.min-width;
            height: i-loading-layout.min-height;

            i-loading-layout := VerticalLayout {
                padding: 8px;
                spacing: 4px;
                i-text := Text {
                    horizontal-alignment: center;
                    text: "Loading...";
                }

                Rectangle {
                    background: black;
                    width: Backend.rom-select-progress * i-text.min-width;
                    height: 2px;
                }
            }
        }
    }
}
